//! Adversarial regression for the arith→EUF fixed-value propagation fix
//! (`model_based_combination` merges an arith-pinned term into its constant's
//! EUF node so congruence fires). 60 QF_UFLIA cases, each verdict CONFIRMED with
//! z3, generated to stress the soundness-critical edges: off-path / decoy fixed
//! terms, distinct-value "diamonds", multiple independent merge classes, deep
//! nested chains, shared-constant vars, negative constants. The hard requirement
//! is ZERO spurious UNSAT (oxiz=unsat where z3=sat) on EITHER driver — the
//! dangerous direction. Run through both the legacy and the §4 hooks driver.
use oxiz_solver::Context;
fn run(s:&str,h:bool)->&'static str{let mut c=Context::new();c.set_timeout_ms(8000);if h{c.set_option("oxiz.use-hooks-driver","true");}match c.execute_script(s){Ok(o)=>o.iter().rev().find_map(|l|match l.trim(){"sat"=>Some("sat"),"unsat"=>Some("unsat"),"unknown"=>Some("unknown"),_=>None}).unwrap_or("unknown"),Err(_)=>"unknown"}}
const CASES:&[(&str,&str,&str)]=&[
("sat_decoy_fixed_term_off_path","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (f 5) 9))\n(assert (<= (f 5) 9))\n(assert (>= (f 3) 9))\n(assert (<= (f 3) 9))\n(assert (= (f (f 1)) 9))\n(check-sat)","sat"),
("unsat_genuine_congruence_value_clash","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (f 5) 9))\n(assert (<= (f 5) 9))\n(assert (= (f (f 1)) 2))\n(check-sat)","unsat"),
("sat_chain_with_isolated_decoys","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 0) 1))\n(assert (<= (f 0) 1))\n(assert (>= (f 1) 2))\n(assert (<= (f 1) 2))\n(assert (>= (f 7) 7))\n(assert (<= (f 7) 7))\n(assert (>= (f 8) 8))\n(assert (<= (f 8) 8))\n(assert (= (f (f 0)) 2))\n(check-sat)","sat"),
("unsat_diamond_equal_args_disequal_results","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(assert (>= (f 1) 3))\n(assert (<= (f 1) 3))\n(assert (>= (f 2) 3))\n(assert (<= (f 2) 3))\n(assert (= (g (f 1)) 0))\n(assert (= (g (f 2)) 1))\n(check-sat)","unsat"),
("sat_diamond_distinct_args_rescued","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(assert (>= (f 1) 3))\n(assert (<= (f 1) 3))\n(assert (>= (f 2) 4))\n(assert (<= (f 2) 4))\n(assert (= (g (f 1)) 0))\n(assert (= (g (f 2)) 1))\n(check-sat)","sat"),
("sat_two_merge_classes_no_crosstalk","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun h (Int) Int)\n(assert (>= (f 1) 10))\n(assert (<= (f 1) 10))\n(assert (>= (f 2) 10))\n(assert (<= (f 2) 10))\n(assert (>= (f 3) 20))\n(assert (<= (f 3) 20))\n(assert (>= (f 4) 20))\n(assert (<= (f 4) 20))\n(assert (= (h (f 1)) 0))\n(assert (= (h (f 2)) 0))\n(assert (= (h (f 3)) 5))\n(assert (= (h (f 4)) 5))\n(check-sat)","sat"),
("unsat_one_merge_class_decoys_present","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun h (Int) Int)\n(assert (>= (f 1) 10))\n(assert (<= (f 1) 10))\n(assert (>= (f 2) 10))\n(assert (<= (f 2) 10))\n(assert (>= (f 3) 20))\n(assert (<= (f 3) 20))\n(assert (>= (f 4) 20))\n(assert (<= (f 4) 20))\n(assert (= (h (f 1)) 0))\n(assert (= (h (f 2)) 1))\n(check-sat)","unsat"),
("sat_fixed_via_shared_constant_var","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(declare-fun y () Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= x 5))\n(assert (<= x 5))\n(assert (>= y 5))\n(assert (<= y 5))\n(assert (= (f 5) x))\n(assert (= (f (f 1)) 5))\n(check-sat)","sat"),
("unsat_three_step_chain_all_needed","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(assert (>= (f 0) 1))\n(assert (<= (f 0) 1))\n(assert (>= (f 1) 2))\n(assert (<= (f 1) 2))\n(assert (= (g 2) 7))\n(assert (= (g (f (f 0))) 8))\n(check-sat)","unsat"),
("sat_distinct_self_apply_chains","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (f 2) 6))\n(assert (<= (f 2) 6))\n(assert (= (f (f 1)) 0))\n(assert (= (f (f 2)) 1))\n(assert (= (f 5) 0))\n(assert (= (f 6) 1))\n(check-sat)","sat"),
("sat_self_loop_fixed_points_distinct","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 1))\n(assert (<= (f 1) 1))\n(assert (>= (f 2) 2))\n(assert (<= (f 2) 2))\n(assert (= (f (f 1)) 1))\n(assert (= (f (f 2)) 2))\n(check-sat)","sat"),
("unsat_swapped_fixed_values_transitive","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 2))\n(assert (<= (f 1) 2))\n(assert (>= (f 2) 1))\n(assert (<= (f 2) 1))\n(assert (= (f (f 1)) (f (f 2))))\n(check-sat)","unsat"),
("deep_self_app_fixpoint_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 1))\n(assert (<= (f 1) 1))\n(assert (not (= (f (f (f (f 1)))) 1)))\n(check-sat)","unsat"),
("fixpoint_other_point_free_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 1))\n(assert (<= (f 1) 1))\n(assert (= (f (f (f (f 1)))) 1))\n(assert (not (= (f 2) 1)))\n(check-sat)","sat"),
("fix_to_nonself_const_deep_free_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (= (f (f (f (f 1)))) 99))\n(check-sat)","sat"),
("mutual_value_cycle_deep_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (f 5) 1))\n(assert (<= (f 5) 1))\n(assert (not (= (f (f (f (f 1)))) 1)))\n(check-sat)","unsat"),
("mutual_fg_4level_chain_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(assert (and (>= (f 1) 2) (<= (f 1) 2)))\n(assert (and (>= (g 2) 3) (<= (g 2) 3)))\n(assert (and (>= (f 3) 4) (<= (f 3) 4)))\n(assert (and (>= (g 4) 5) (<= (g 4) 5)))\n(assert (not (= (g (f (g (f 1)))) 5)))\n(check-sat)","unsat"),
("mutual_fg_chain_top_free_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(assert (and (>= (f 1) 2) (<= (f 1) 2)))\n(assert (and (>= (g 2) 3) (<= (g 2) 3)))\n(assert (and (>= (f 3) 4) (<= (f 3) 4)))\n(assert (= (g (f (g (f 1)))) 100))\n(check-sat)","sat"),
("unfixed_range_no_merge_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 1))\n(assert (<= (f 1) 3))\n(assert (= (f (f (f 1))) 7))\n(assert (not (= (f 1) (f (f 1)))))\n(check-sat)","sat"),
("fixpoint_value_conflict_via_merge_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 1))\n(assert (<= (f 1) 1))\n(assert (>= (f (f 1)) 2))\n(check-sat)","unsat"),
("value_2cycle_consistent_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (and (>= (f 1) 2) (<= (f 1) 2)))\n(assert (and (>= (f 2) 1) (<= (f 2) 1)))\n(assert (= (f (f (f (f 1)))) 1))\n(assert (= (f (f (f 1))) 2))\n(check-sat)","sat"),
("value_2cycle_wrong_deep_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (and (>= (f 1) 2) (<= (f 1) 2)))\n(assert (and (>= (f 2) 1) (<= (f 2) 1)))\n(assert (= (f (f (f (f 1)))) 2))\n(check-sat)","unsat"),
("distinct_fixes_collision_free_deep_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (and (>= (f 1) 10) (<= (f 1) 10)))\n(assert (and (>= (f 10) 20) (<= (f 10) 20)))\n(assert (and (>= (f 20) 30) (<= (f 20) 30)))\n(assert (and (>= (f 30) 40) (<= (f 30) 40)))\n(assert (and (>= (f 5) 10) (<= (f 5) 10)))\n(assert (= (f (f (f (f 1)))) 40))\n(check-sat)","sat"),
("mutual_fg_5level_value_conflict_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(assert (and (>= (f 0) 1) (<= (f 0) 1)))\n(assert (and (>= (g 1) 0) (<= (g 1) 0)))\n(assert (>= (g (f (g (f 0)))) 5))\n(check-sat)","unsat"),
("double_neg_fold_drives_sound_congruence__unsat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(assert (= x (- (- 3))))\n(assert (>= (f x) 5))\n(assert (<= (f x) 5))\n(assert (distinct (f (f x)) (f 5)))\n(check-sat)","unsat"),
("double_neg_fold__congruence_explicit___denied__unsat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(assert (= x (- (- 3))))\n(assert (>= (f x) 5))\n(assert (<= (f x) 5))\n(assert (= (f (f x)) (f 5)))\n(assert (distinct (f (f x)) (f 5)))\n(check-sat)","unsat"),
("negative_fixed_value__2_drives_congruence__unsat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(assert (>= (f x) (- 2)))\n(assert (<= (f x) (- 2)))\n(assert (distinct (f (f x)) (f (- 2))))\n(check-sat)","unsat"),
("negative_fixed_value__consistent_congruence__sat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(assert (>= (f x) (- 2)))\n(assert (<= (f x) (- 2)))\n(assert (= (f (f x)) (f (- 2))))\n(assert (> (f 100) 1000))\n(check-sat)","sat"),
("___0__normalization__consistent__sat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(assert (= x (- 0)))\n(assert (>= (f x) (- 0)))\n(assert (<= (f x) 0))\n(assert (= (f (f 0)) (f x)))\n(check-sat)","sat"),
("two_distinct_large_negatives_must_NOT_merge__sat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(declare-fun b () Int)\n(assert (>= (f a) (- 1000000000)))\n(assert (<= (f a) (- 1000000000)))\n(assert (>= (f b) (- 1000000001)))\n(assert (<= (f b) (- 1000000001)))\n(assert (= (f (f a)) (f (f b))))\n(check-sat)","sat"),
("opposite_sign_fixed_values_must_stay_distinct__sat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(declare-fun y () Int)\n(assert (>= (f x) (- 3)))\n(assert (<= (f x) (- 3)))\n(assert (>= (f y) 3))\n(assert (<= (f y) 3))\n(assert (distinct (f (f x)) (f (f y))))\n(check-sat)","sat"),
("double_neg_both_sides_merge__distinct_domain_points__sat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(declare-fun y () Int)\n(assert (>= (f x) (- (- 7))))\n(assert (<= (f x) 7))\n(assert (>= (f y) 7))\n(assert (<= (f y) (- (- 7))))\n(assert (= (f (f x)) (f (f y))))\n(assert (distinct x y))\n(check-sat)","sat"),
("triple_neg_fold_to__7_drives_congruence__unsat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(assert (>= (f x) (- (- (- 7)))))\n(assert (<= (f x) (- 7)))\n(assert (distinct (f (f x)) (f (- 7))))\n(check-sat)","unsat"),
("______2__x__fold_to_negative__consistent__sat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(declare-fun z () Int)\n(assert (= x 3))\n(assert (= z (* (- 2) x)))\n(assert (>= (f z) (- 6)))\n(assert (<= (f z) (- 6)))\n(assert (= (f (f z)) (f (- 6))))\n(assert (distinct (f 0) (f z)))\n(check-sat)","sat"),
("negative_zero_is_the_same_domain_point__unsat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (distinct (f 0) (f (- 0))))\n(check-sat)","unsat"),
("negative_fixed_value_with_explicit_f__5__f_5__values__sat_","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun x () Int)\n(assert (>= (f x) (- 5)))\n(assert (<= (f x) (- 5)))\n(assert (= (f 5) 100))\n(assert (= (f (- 5)) 200))\n(assert (= (f (f x)) (f (- 5))))\n(check-sat)","sat"),
("fixed_value_congruence_to_explicit_eq_diseq","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (= (f 5) a))\n(assert (distinct (f (f 1)) a))\n(check-sat)","unsat"),
("fixed_value_congruence_eq_satisfiable","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (= (f 5) a))\n(assert (= (f (f 1)) a))\n(check-sat)","sat"),
("fixed_value_diseq_of_bool_predicate","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun p (Int) Bool)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (p (f 1)))\n(assert (not (p 5)))\n(check-sat)","unsat"),
("fixed_value_predicate_distinct_arg_satisfiable","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun p (Int) Bool)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (p (f 1)))\n(assert (not (p 6)))\n(check-sat)","sat"),
("two_args_fixed_same_value_distinct_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (f 2) 5))\n(assert (<= (f 2) 5))\n(assert (distinct (f 1) (f 2)))\n(check-sat)","unsat"),
("two_args_fixed_same_value_consistent_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun h (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (f 2) 5))\n(assert (<= (f 2) 5))\n(assert (= (h (f 1)) (h (f 2))))\n(assert (distinct (f 1) 4))\n(check-sat)","sat"),
("preexisting_diseq_edge_survives_merge_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(declare-fun p (Int) Bool)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (= a 6))\n(assert (distinct (f 1) a))\n(assert (= (p (f 1)) (p 5)))\n(assert (distinct (f (f 1)) (f a)))\n(check-sat)","sat"),
("fixed_cycle_with_diseq_and_predicate_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun p (Int) Bool)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (f 5) 5))\n(assert (<= (f 5) 5))\n(assert (= (f (f 1)) (f 1)))\n(assert (distinct (f 1) 4))\n(assert (p (f 1)))\n(assert (not (p 4)))\n(check-sat)","sat"),
("non_tight_bounds_must_not_fix_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 6))\n(assert (= (f 5) a))\n(assert (distinct (f (f 1)) a))\n(check-sat)","sat"),
("fixed_via_arith_glue_distinct_images_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(declare-fun k (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (>= (g 1) 10))\n(assert (<= (g 1) 10))\n(assert (= (f 1) (- (g 1) 5)))\n(assert (= (k (f 1)) (k 5)))\n(assert (distinct (k 5) (k 10)))\n(check-sat)","sat"),
("fixed_value_collision_zero_vs_one_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (= (g (f 1)) 0))\n(assert (= (g 5) 1))\n(check-sat)","unsat"),
("fixed_value_fresh_diseq_target_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(declare-fun c () Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (= (f 5) a))\n(assert (distinct (f (f 1)) c))\n(assert (distinct a c))\n(check-sat)","sat"),
("fix_must_fire_congruence_false_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (not (= (f (f 1)) (f 5))))\n(check-sat)\n","unsat"),
("fix_consistent_congruence_true_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 5))\n(assert (<= (f 1) 5))\n(assert (= (f (f 1)) (f 5)))\n(check-sat)\n","sat"),
("two_terms_same_value_zero_congruence_false_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(declare-fun a () Int)\n(declare-fun b () Int)\n(assert (= (f a) 0))\n(assert (= (f b) 0))\n(assert (not (= (g (f a)) (g (f b)))))\n(check-sat)\n","unsat"),
("two_terms_value_zero_via_bounds_consistent_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(declare-fun a () Int)\n(declare-fun b () Int)\n(assert (<= (f a) 0))\n(assert (>= (f a) 0))\n(assert (<= (f b) 0))\n(assert (>= (f b) 0))\n(assert (= (g (f a)) (g (f b))))\n(check-sat)\n","sat"),
("close_distinct_neg1_vs_0_disequal_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(declare-fun a () Int)\n(declare-fun b () Int)\n(assert (= (f a) (- 1)))\n(assert (= (f b) 0))\n(assert (not (= (g (f a)) (g (f b))))) \n(check-sat)\n","sat"),
("neg1_fixedpoint_self_congruence_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (= (f (- 1)) (- 1)))\n(assert (not (= (f (f (- 1))) (- 1))))\n(check-sat)\n","unsat"),
("large_value_million_congruence_false_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(assert (>= (f 1) 1000000))\n(assert (<= (f 1) 1000000))\n(assert (not (= (f (f 1)) (f 1000000))))\n(check-sat)\n","unsat"),
("fixed_value_propagates_into_constant_app_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(assert (= (f a) 5))\n(assert (= (f 5) 7))\n(assert (= (f (f a)) 9))\n(check-sat)\n","unsat"),
("distinct_value_pairs_coincide_at_5_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(declare-fun a () Int)\n(declare-fun b () Int)\n(assert (>= (f a) 5))\n(assert (<= (f a) 5))\n(assert (= (f b) (+ 2 3)))\n(assert (not (= (g (f a)) (g (f b)))))\n(check-sat)\n","unsat"),
("fixed_value_consistent_chain_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun a () Int)\n(assert (= (f a) 5))\n(assert (= (f 5) 7))\n(assert (= (f (f a)) 7))\n(check-sat)\n","sat"),
("same_and_distinct_values_mixed_sat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(declare-fun a () Int)\n(declare-fun b () Int)\n(declare-fun c () Int)\n(assert (>= (f a) 1))\n(assert (<= (f a) 1))\n(assert (= (f b) 1))\n(assert (= (f c) 0))\n(assert (= (g (f a)) (g (f b))))\n(assert (not (= (g (f a)) (g (f c)))))\n(check-sat)\n","sat"),
("symbolic_fixed_value_congruence_false_unsat","(set-logic QF_UFLIA)\n(declare-fun f (Int) Int)\n(declare-fun g (Int) Int)\n(declare-fun a () Int)\n(declare-fun b () Int)\n(declare-fun k () Int)\n(assert (= k 3))\n(assert (= (f a) k))\n(assert (= (f b) k))\n(assert (not (= (g (f a)) (g (f b)))))\n(check-sat)\n","unsat"),
];
#[test] fn adv60(){let mut spur_unsat=vec![];let mut mism=vec![];for &(name,s,z3) in CASES{let l=run(s,false);let h=run(s,true);if l=="sat"&&z3=="unsat"||h=="sat"&&z3=="unsat"{ /* oxiz too weak vs z3 unsat: spurious SAT, not dangerous here */ }if (z3=="sat")&&(l=="unsat"||h=="unsat"){spur_unsat.push(format!("{name} legacy={l} hooks={h} z3={z3}"));}if l!=z3||h!=z3{mism.push(format!("{name} legacy={l} hooks={h} z3={z3}"));}}
println!("total={} mismatches={} SPURIOUS_UNSAT={}",CASES.len(),mism.len(),spur_unsat.len());
for m in &mism{println!("  MISMATCH {m}");}
assert!(spur_unsat.is_empty(),"SPURIOUS UNSAT (dangerous): {:?}",spur_unsat);}